'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("InAI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property InAIUpdate() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("InAIUpdate", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property inventor() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("inventor", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 保存全部161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("保存全部161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 保存全部323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("保存全部323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 保存关闭161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("保存关闭161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 保存关闭323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("保存关闭323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 修改文件iProperty161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("修改文件iProperty161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 修改文件iProperty323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("修改文件iProperty323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 修改部件iProperty161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("修改部件iProperty161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 修改部件iProperty323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("修改部件iProperty323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 全部另存为161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("全部另存为161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 全部另存为323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("全部另存为323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 关于161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("关于161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 关于323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("关于323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 关闭工程图161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("关闭工程图161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 关闭工程图323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("关闭工程图323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 关闭部件161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("关闭部件161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 关闭部件323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("关闭部件323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 关闭零件161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("关闭零件161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 关闭零件323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("关闭零件323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 刷新引用161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("刷新引用161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 刷新引用323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("刷新引用323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 另存为Dwg161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("另存为Dwg161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 另存为Dwg323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("另存为Dwg323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 另存为Pdf161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("另存为Pdf161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 另存为Pdf323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("另存为Pdf323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 对称件iProperty161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("对称件iProperty161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 对称件iProperty323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("对称件iProperty323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 对齐原始坐标面161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("对齐原始坐标面161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 对齐原始坐标面323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("对齐原始坐标面323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 导出平面BOM161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("导出平面BOM161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 导出平面BOM323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("导出平面BOM323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 导出树形BOM161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("导出树形BOM161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 导出树形BOM323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("导出树形BOM323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 尺寸圆整161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("尺寸圆整161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 尺寸圆整323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("尺寸圆整323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 工程图161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("工程图161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 工程图323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("工程图323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 帮助161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("帮助161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 帮助323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("帮助323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 微信() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("微信", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 快速打开161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("快速打开161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 快速打开323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("快速打开323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打印161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打印161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打印323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打印323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打开ERP数据文件161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打开ERP数据文件161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打开ERP数据文件323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打开ERP数据文件323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打开全部工程图161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打开全部工程图161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打开全部工程图323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打开全部工程图323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打开文件夹161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打开文件夹161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打开文件夹323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打开文件夹323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 批量另存为161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("批量另存为161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 批量另存为323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("批量另存为323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 提取iPro修改文件名161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("提取iPro修改文件名161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 提取iPro修改文件名323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("提取iPro修改文件名323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 插入序号161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("插入序号161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 插入序号323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("插入序号323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 支付宝() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("支付宝", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 新建序号161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("新建序号161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 新建序号323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("新建序号323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 更改文件名161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("更改文件名161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 更改文件名323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("更改文件名323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 更改镜像文件名161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("更改镜像文件名161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 更改镜像文件名323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("更改镜像文件名323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 查找缺失文件的部件161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("查找缺失文件的部件161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 查找缺失文件的部件323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("查找缺失文件的部件323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 查找部件161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("查找部件161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 查找部件323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("查找部件323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 查询材料编码161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("查询材料编码161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 查询材料编码323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("查询材料编码323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 检查序号完整性161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("检查序号完整性161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 检查序号完整性323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("检查序号完整性323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 检查是否有工程图161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("检查是否有工程图161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 检查是否有工程图323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("检查是否有工程图323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 添加直径161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("添加直径161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 添加直径323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("添加直径323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清理旧版文件161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清理旧版文件161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清理旧版文件323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清理旧版文件323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清除日期161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清除日期161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清除日期323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清除日期323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清除签字161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清除签字161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清除签字323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清除签字323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 生成图号161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("生成图号161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 生成图号323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("生成图号323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 移动指定文件161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("移动指定文件161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 移动指定文件323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("移动指定文件323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 空白161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("空白161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 空白323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("空白323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 统计161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("统计161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 统计323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("统计323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 自定义日期161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("自定义日期161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 自定义日期323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("自定义日期323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 自定义签字161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("自定义签字161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 自定义签字323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("自定义签字323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置BOM结构161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置BOM结构161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置BOM结构323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置BOM结构323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置描述161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置描述161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置描述323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置描述323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置日期161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置日期161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置日期323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置日期323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置材料编码161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置材料编码161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置材料编码323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置材料编码323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置比例161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置比例161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置比例323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置比例323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置签字161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置签字161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置签字323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置签字323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 调整IPro顺序161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("调整IPro顺序161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 调整IPro顺序323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("调整IPro顺序323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 还原旧图161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("还原旧图161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 还原旧图323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("还原旧图323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 部件161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("部件161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 部件323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("部件323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 部件替换文件名161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("部件替换文件名161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 部件替换文件名323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("部件替换文件名323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 重写BOM161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("重写BOM161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 重写BOM323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("重写BOM323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 量产iPropertys161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("量产iPropertys161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 量产iPropertys323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("量产iPropertys323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 零件161624() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("零件161624", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 零件323224() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("零件323224", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
