'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("XHTool.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property inventor16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("inventor16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property inventor32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("inventor32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property inventor64() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("inventor64", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property IPro16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IPro16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property IPro32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IPro32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property XHTool() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XHTool", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property XHTool24() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("XHTool24", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property XHTool32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("XHTool32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property XHTool48() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("XHTool48", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 不可见16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("不可见16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 交换16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("交换16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 交换32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("交换32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 保存全部16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("保存全部16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 保存全部32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("保存全部32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 保存关闭16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("保存关闭16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 保存关闭32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("保存关闭32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 修改文件iProperty16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("修改文件iProperty16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 修改文件iProperty32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("修改文件iProperty32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 修改部件iProperty16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("修改部件iProperty16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 修改部件iProperty32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("修改部件iProperty32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 全部另存为16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("全部另存为16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 全部另存为32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("全部另存为32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 全部尺寸居中16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("全部尺寸居中16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 全部尺寸居中32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("全部尺寸居中32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 关于16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("关于16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 关于32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("关于32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 关闭文档16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("关闭文档16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 关闭文档32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("关闭文档32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 其他格式16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("其他格式16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 其他格式32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("其他格式32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 内存文件16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("内存文件16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 内存文件32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("内存文件32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 创建展开16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("创建展开16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 创建展开32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("创建展开32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 创建工程图16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("创建工程图16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 创建工程图32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("创建工程图32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 创建截图16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("创建截图16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 创建截图32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("创建截图32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 刷新引用16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("刷新引用16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 刷新引用32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("刷新引用32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 前进16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("前进16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 另存为Dwg16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("另存为Dwg16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 另存为Dwg32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("另存为Dwg32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 另存为Dxf16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("另存为Dxf16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 另存为Dxf32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("另存为Dxf32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 另存为Pdf16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("另存为Pdf16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 另存为Pdf32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("另存为Pdf32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 可写16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("可写16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 可写32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("可写32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 可见16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("可见16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 可见32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("可见32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 同名替换16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("同名替换16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 同名替换32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("同名替换32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 后退16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("后退16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 图片16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("图片16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 复制16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("复制16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 复制32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("复制32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 对称件iProperty16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("对称件iProperty16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 对称件iProperty32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("对称件iProperty32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 对齐原始坐标面16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("对齐原始坐标面16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 对齐原始坐标面32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("对齐原始坐标面32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 导入BOM示例() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("导入BOM示例", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 导入ERP到BOM16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("导入ERP到BOM16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 导入ERP到BOM32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("导入ERP到BOM32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 导入材料编码16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("导入材料编码16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 导入材料编码32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("导入材料编码32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 导出平面BOM16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("导出平面BOM16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 导出平面BOM32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("导出平面BOM32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 导出树形BOM16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("导出树形BOM16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 导出树形BOM32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("导出树形BOM32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 尺寸圆整16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("尺寸圆整16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 尺寸圆整32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("尺寸圆整32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 尺寸居中16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("尺寸居中16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 尺寸居中32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("尺寸居中32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 居中对齐16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("居中对齐16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 居中对齐32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("居中对齐32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 工程图16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("工程图16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 工程图32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("工程图32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 帮助16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("帮助16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 帮助32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("帮助32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 当前部件16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("当前部件16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 当前部件32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("当前部件32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 微信() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("微信", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 快速打印16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("快速打印16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 快速打印32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("快速打印32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打印16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打印16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打印32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打印32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打开ERP数据文件16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打开ERP数据文件16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打开ERP数据文件32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打开ERP数据文件32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打开文件16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打开文件16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打开文件32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打开文件32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打开文件夹16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打开文件夹16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 打开文件夹32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("打开文件夹32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 批量打印16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("批量打印16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 批量打印32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("批量打印32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 技术要求16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("技术要求16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 技术要求32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("技术要求32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 抑制约束16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("抑制约束16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 按列表打开16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("按列表打开16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 按列表打开32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("按列表打开32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 提取iPro修改文件名16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("提取iPro修改文件名16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 提取iPro修改文件名32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("提取iPro修改文件名32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 插入序号16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("插入序号16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 插入序号32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("插入序号32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 支付宝() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("支付宝", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 新建序号16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("新建序号16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 新建序号32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("新建序号32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 暂停16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("暂停16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 更改文件名16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("更改文件名16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 更改文件名32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("更改文件名32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 更改材料16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("更改材料16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 更改镜像文件名16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("更改镜像文件名16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 更改镜像文件名32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("更改镜像文件名32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 替换为库文件16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("替换为库文件16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 替换为库文件32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("替换为库文件32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 替换衍生16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("替换衍生16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 替换衍生32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("替换衍生32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 查找替换16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("查找替换16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 查找替换32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("查找替换32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 查找缺失文件的部件16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("查找缺失文件的部件16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 查找缺失文件的部件32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("查找缺失文件的部件32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 查询16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("查询16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 查询32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("查询32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 标准件可见性16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("标准件可见性16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 标准件可见性32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("标准件可见性32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 标记展开图螺纹16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("标记展开图螺纹16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 标记展开图螺纹32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("标记展开图螺纹32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 标题栏16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("标题栏16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 标题栏32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("标题栏32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 格式分类16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("格式分类16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 格式转换16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("格式转换16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 格式转换32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("格式转换32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 检查序号完整性16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("检查序号完整性16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 检查序号完整性32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("检查序号完整性32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 检查是否有工程图16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("检查是否有工程图16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 检查是否有工程图32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("检查是否有工程图32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 添加16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("添加16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 添加直径16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("添加直径16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 添加直径32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("添加直径32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清理旧版文件16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清理旧版文件16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清理旧版文件32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清理旧版文件32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清空列表16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清空列表16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清空列表32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清空列表32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清除日期16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清除日期16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清除日期32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清除日期32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清除签字16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清除签字16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清除签字32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清除签字32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清除随机颜色16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清除随机颜色16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 清除随机颜色32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("清除随机颜色32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 生成图号16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("生成图号16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 生成图号32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("生成图号32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 确定16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("确定16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 移出文件16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("移出文件16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 移动指定文件16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("移动指定文件16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 移动指定文件32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("移动指定文件32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 空白16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("空白16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 空白32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("空白32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 统计16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("统计16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 统计32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("统计32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 编辑尺寸16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("编辑尺寸16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 编辑尺寸32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("编辑尺寸32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 自动重建序号16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("自动重建序号16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 自动重建序号32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("自动重建序号32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 自定义日期16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("自定义日期16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 自定义日期32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("自定义日期32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 自定义签字16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("自定义签字16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 自定义签字32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("自定义签字32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 自适应16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("自适应16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 自适应32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("自适应32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设值随机颜色16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设值随机颜色16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设值随机颜色32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设值随机颜色32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置BOM结构16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置BOM结构16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置BOM结构32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置BOM结构32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置属性16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置属性16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置属性32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置属性32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置描述16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置描述16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置描述32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置描述32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置日期16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置日期16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置日期32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置日期32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置材料编码16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置材料编码16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置材料编码32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置材料编码32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置比例16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置比例16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置比例32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置比例32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置签字16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置签字16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置签字32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("设置签字32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 距离对齐16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("距离对齐16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 距离对齐32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("距离对齐32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 还原16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("还原16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 还原旧图16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("还原旧图16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 还原旧图32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("还原旧图32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 选择16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("选择16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 选择一32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("选择一32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 选择二32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("选择二32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 选择面和边32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("选择面和边32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 部件16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("部件16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 部件32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("部件32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 部件替换文件名16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("部件替换文件名16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 部件替换文件名32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("部件替换文件名32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 配合16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("配合16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 采购来源16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("采购来源16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 采购来源32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("采购来源32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 重写BOM16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("重写BOM16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 重写BOM32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("重写BOM32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 量产iPropertys16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("量产iPropertys16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 量产iPropertys32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("量产iPropertys32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 零件16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("零件16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 零件32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("零件32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 静默16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("静默16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 静默32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("静默32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 驱动测量16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("驱动测量16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 驱动测量32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("驱动测量32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
